### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by LX2035** [LubanCat/LubanCatWrt#6]
### Describe the bug

按照官方教程编译不过，不清楚是不是有什么变动了？

### OpenWrt version

main分支

### OpenWrt target/subtarget

main分支

### Device

cat2n

### Image kind

Official downloaded image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by erd-yunmu** [comment]
下载代码
`git clone https://github.com/LubanCat/LubanCatWrt`

执行
`./scripts/feeds update -a`
`./scripts/feeds install -a`


配置menuconfig
`cat config/lubancat_defconfig > .config`
`make menuconfig`


下载dl
`make -j8 download`

执行编译
`make -j$(($(nproc) + 1))
`
最后看看是不是可以编译过。

**Comment by LX2035** [comment]
似乎是编译这个包的时候报错了：





使用make V=s -j1详细报错如下：


patchelf.cc: In instantiation of 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]':
patchelf.cc:2208:28:&nbsp; &nbsp;required from 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::renameDynamicSymbols(const std::unordered_map<std::basic_string_view<char&gt;, std::__cxx11::basic_string<char&gt; &gt;&amp;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]'
patchelf.cc:2442:9:&nbsp; &nbsp;required from 'void patchElf2(ElfFile&amp;&amp;, const FileContents&amp;, const string&amp;) [with ElfFile = ElfFile<Elf64_Ehdr, Elf64_Phdr, Elf64_Shdr, long unsigned int, long unsigned int, Elf64_Dyn, Elf64_Sym, short unsigned int, Elf64_Verdef, Elf64_Verdaux, Elf64_Verneed, Elf64_Vernaux, Elf64_Rel, Elf64_Rela, 64&gt;; FileContents = std::shared_ptr<std::vector<unsigned char&gt; &gt;; std::__cxx11::string = std::__cxx11::basic_string<char&gt;]'
patchelf.cc:2465:256:&nbsp; &nbsp;required from here
patchelf.cc:2102:37: error: use of 'auto span<T&gt;::size() const [with T = long unsigned int]' before deduction of 'auto'
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;size_t idx = (h / ElfClass) % ght.m_bloomFilters.size();
In file included from patchelf.cc:47:0:
patchelf.h:226:10: error: 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::changeRelocTableSymIds(const Elf_Shdr&amp;, RemapFn&amp;&amp;) [with ElfRelType = Elf32_Rel; RemapFn = ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]::<lambda(auto:7&amp;)&gt;&amp;; Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]', declared using local type 'ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]::<lambda(auto:7&amp;)&gt;', is used but never defined [-fpermissive]
&nbsp; &nbsp; &nbsp;void changeRelocTableSymIds(const Elf_Shdr&amp; shdr, RemapFn&amp;&amp; old2newSymId)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^~~~~~~~~~~~~~~~~~~~~~
patchelf.h:226:10: error: 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::changeRelocTableSymIds(const Elf_Shdr&amp;, RemapFn&amp;&amp;) [with ElfRelType = Elf32_Rela; RemapFn = ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]::<lambda(auto:7&amp;)&gt;&amp;; Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]', declared using local type 'ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf32_Ehdr; Elf_Phdr = Elf32_Phdr; Elf_Shdr = Elf32_Shdr; Elf_Addr = unsigned int; Elf_Off = unsigned int; Elf_Dyn = Elf32_Dyn; Elf_Sym = Elf32_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf32_Verdef; Elf_Verdaux = Elf32_Verdaux; Elf_Verneed = Elf32_Verneed; Elf_Vernaux = Elf32_Vernaux; Elf_Rel = Elf32_Rel; Elf_Rela = Elf32_Rela; unsigned int ElfClass = 32]::<lambda(auto:7&amp;)&gt;', is used but never defined [-fpermissive]
patchelf.h:226:10: error: 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::changeRelocTableSymIds(const Elf_Shdr&amp;, RemapFn&amp;&amp;) [with ElfRelType = Elf64_Rel; RemapFn = ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]::<lambda(auto:7&amp;)&gt;&amp;; Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]', declared using local type 'ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]::<lambda(auto:7&amp;)&gt;', is used but never defined [-fpermissive]
patchelf.h:226:10: error: 'void ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::changeRelocTableSymIds(const Elf_Shdr&amp;, RemapFn&amp;&amp;) [with ElfRelType = Elf64_Rela; RemapFn = ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]::<lambda(auto:7&amp;)&gt;&amp;; Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]', declared using local type 'ElfFile<Elf_Ehdr, Elf_Phdr, Elf_Shdr, Elf_Addr, Elf_Off, Elf_Dyn, Elf_Sym, Elf_Versym, Elf_Verdef, Elf_Verdaux, Elf_Verneed, Elf_Vernaux, Elf_Rel, Elf_Rela, ElfClass&gt;::rebuildGnuHashTable(span<char&gt;, span<Elf_Sym&gt;) [with Elf_Ehdr = Elf64_Ehdr; Elf_Phdr = Elf64_Phdr; Elf_Shdr = Elf64_Shdr; Elf_Addr = long unsigned int; Elf_Off = long unsigned int; Elf_Dyn = Elf64_Dyn; Elf_Sym = Elf64_Sym; Elf_Versym = short unsigned int; Elf_Verdef = Elf64_Verdef; Elf_Verdaux = Elf64_Verdaux; Elf_Verneed = Elf64_Verneed; Elf_Vernaux = Elf64_Vernaux; Elf_Rel = Elf64_Rel; Elf_Rela = Elf64_Rela; unsigned int ElfClass = 64]::<lambda(auto:7&amp;)&gt;', is used but never defined [-fpermissive]
Makefile:380: recipe for target 'patchelf.o' failed
make[5]: *** [patchelf.o] Error 1
make[5]: Leaving directory '/home/lx/LubanCatWrt/build_dir/host/patchelf-0.18.0/src'
Makefile:472: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/home/lx/LubanCatWrt/build_dir/host/patchelf-0.18.0'
Makefile:30: recipe for target '/home/lx/LubanCatWrt/build_dir/host/patchelf-0.18.0/.built' failed
make[3]: *** [/home/lx/LubanCatWrt/build_dir/host/patchelf-0.18.0/.built] Error 2
make[3]: Leaving directory '/home/lx/LubanCatWrt/tools/patchelf'
time: tools/patchelf/compile#0.82#0.15#1.00
&nbsp; &nbsp; ERROR: tools/patchelf failed to build.
tools/Makefile:224: recipe for target 'tools/patchelf/compile' failed
make[2]: *** [tools/patchelf/compile] Error 1
make[2]: Leaving directory '/home/lx/LubanCatWrt'
tools/Makefile:222: recipe for target '/home/lx/LubanCatWrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyynynyyyyyyynyyynnynyynnynnyyyyyyyyyyyyyyyyynynnyyyyyyy' failed
make[1]: *** [/home/lx/LubanCatWrt/staging_dir/host/stamp/.tools_compile_nyyynyynnnyyynynyyyyyyynyyynnynyynnynnyyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/lx/LubanCatWrt'



水语茗言
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LubanCat/LubanCatWrt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月25日(星期二) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LubanCat/LubanCatWrt] 编译不过 (Issue #6)





 
下载代码
 git clone https://github.com/LubanCat/LubanCatWrt
 
执行
 ./scripts/feeds update -a
 ./scripts/feeds install -a
 
配置menuconfig
 cat config/lubancat_defconfig &gt; .config
 make menuconfig
 
下载dl
 make -j8 download
 
执行编译
 make -j$(($(nproc) + 1)) 
 最后看看是不是可以编译过。

**Comment by erd-yunmu** [comment]
请按照我提供编译方法。删了源码重新下载，代码跟着我操作

> 下载代码 `git clone https://github.com/LubanCat/LubanCatWrt`
> 
> 执行 `./scripts/feeds update -a` `./scripts/feeds install -a`
> 
> 配置menuconfig `cat config/lubancat_defconfig > .config` `make menuconfig`
> 
> 下载dl `make -j8 download`
> 
> 执行编译 `make -j$(($(nproc) + 1)) ` 最后看看是不是可以编译过。

**Comment by LX2035** [comment]
感谢回复！是按照您的步骤来的，感觉区别就是没删源码了，下载dl这一步我是否可以把原来代码的dl复制过去呢？因为dl下载确实需要很长时间😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月26日(周三) 上午8:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [LubanCat/LubanCatWrt] 编译不过 (Issue #6)




 
请按照我提供编译方法。删了源码重新下载，代码跟着我操作
  
下载代码 git clone https://github.com/LubanCat/LubanCatWrt
 
执行 ./scripts/feeds update -a ./scripts/feeds install -a
 
配置menuconfig cat config/lubancat_defconfig &gt; .config make menuconfig
 
下载dl make -j8 download
 
执行编译 make -j$(($(nproc) + 1))  最后看看是不是可以编译过。

**Comment by erd-yunmu** [comment]
可以的
