### ISSUE TITLE
关于鲁班猫2N Openwrt 编译过程中的问题

### ISSUE THREAD

**Issue by Jay-9527** [LubanCat/LubanCatWrt#9]
/home/adiao/LubanCatWrt/include/prereq.mk:9: recipe for target 'prereq' failed
Prerequisite check failed. Use FORCE=1 to override.
/home/adiao/LubanCatWrt/include/toplevel.mk:181: recipe for target '/home/adiao/LubanCatWrt/staging_dir/host/.prereq-build' failed
make: *** [/home/adiao/LubanCatWrt/staging_dir/host/.prereq-build] Error 1
**************download all packages***********************

Build dependency: Please install Python >= 3.7
Build dependency: Please install Python >= 3.7
Build dependency: Please install the Python3 distutils module
Build dependency: Please install the Python3 stdlib module

/home/adiao/LubanCatWrt/include/prereq.mk:9: recipe for target 'prereq' failed
Prerequisite check failed. Use FORCE=1 to override.
/home/adiao/LubanCatWrt/include/toplevel.mk:181: recipe for target '/home/adiao/LubanCatWrt/staging_dir/host/.prereq-build' failed
make: *** [/home/adiao/LubanCatWrt/staging_dir/host/.prereq-build] Error 1

这是搞什么咯？我的使用的环境是Ubuntu 18.04 来进行编译。

**Comment by sanshian** [comment]
安装 Python3 依赖，版本要3.7+

**Comment by Jay-9527** [comment]
可是底下那个错误是怎么回事？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月22日(星期一) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LubanCat/LubanCatWrt] 关于鲁班猫2N Openwrt 编译过程中的问题 (Issue #9)





 
安装 Python3 依赖，版本要3.7+
